project_name: Proyecto Válido
project_description: Este es un proyecto de prueba válido
project_purpose: Probar que al cargar este proyecto no se entra en pánico
programming_language: Go
organizational_unit: Interno
package_dependencies:
  os:
  - pkg1
  - pkg2
  - pkg3
build_dependencies:
  os:
  - pkg1
  - pkg2
  - pkg3
