project_name: oasproj
project_description: Maneja los proyectos de la OAS
project_purpose: Estandarizar el proceso de desarrollo de la OAS
project_framework: cli
programming_language: Go
organizational_unit: Interno
package_dependencies:
  os:
  - gcc
  - git
  - vim
  - make
  - ruby
  - golang
  - rpm-sign
  - rpm-build
  - ruby-devel
build_dependencies:
  os:
  - gcc
  - git
  - vim
  - make
  - ruby
  - golang
  - rpm-sign
  - rpm-build
  - ruby-devel
  gem:
  - fpm
  - travis
  go:
  - github.com/mitchellh/gox
